name: When author added, notify Slack
on:
  push:
    branches:
      - main
    paths:
      - scripts/author_list.csv
jobs:
  slack:
    name: notify-slack
    runs-on: ubuntu-latest
    
    steps:
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        slack_message: 'We have a new pathway author! Please reach out and welcome them. Check the diff linked below to identify new additions.'
